Repository inclusive-design/idrc, pull requests merged in 2021-12, with the labels that each got.

#201 GH-166: Integrate UI Options (resolves #166)
  .eleventy.js
  .github/workflows/backstop.yml
  backstop_data/bitmaps_reference/backstop_default_Repertoire_0_document_0_phone.png
  backstop_data/bitmaps_reference/backstop_default_Repertoire_0_document_1_tablet.png
  backstop_data/bitmaps_reference/backstop_default_Repertoire_0_document_2_desktop.png
  netlify.toml
  package-lock.json
  package.json
  src/_includes/layouts/base.njk
  src/_includes/partials/global/scripts.njk
  src/_includes/partials/global/stylesheets.njk
  src/_includes/svg/filters.svg
  src/assets/styles/app.scss
  src/assets/styles/base/_base.scss
  src/assets/styles/base/_typography.scss
  src/assets/styles/components/_brand.scss
  src/assets/styles/components/_button.scss
  src/assets/styles/components/_image.scss
  src/assets/styles/components/_metadata.scss
  src/assets/styles/components/_nav--secondary.scss
  src/assets/styles/components/_nav.scss
  src/assets/styles/components/_pagination.scss
  src/assets/styles/layout/_footer.scss
  src/assets/styles/layout/_header.scss
  src/assets/styles/pages/_404.scss
  src/assets/styles/pages/_generic.scss
  src/assets/styles/pages/_history.scss
  src/assets/styles/pages/_home.scss
  src/assets/styles/pages/_news-ideas.scss
  src/assets/styles/pages/_projects-tools.scss
  src/assets/styles/pages/_team.scss
  src/assets/styles/vendors/_uio.scss
  src/robots.njk
  src/sitemap.njk
Labels: enhancement

#260 chore: switch from JSDom to Linkedom (see fluid-project/trivet#115)
  package-lock.json
  package.json
  src/transforms/parse.js
Labels: dependencies, enhancement

#263 ci: add autoreleaser tool
  .github/workflows/release.yml
  CHANGELOG.md
Labels: documentation, enhancement
