Repository inclusive-design/idrc, pull requests merged in 2023-08, with the labels that each got.

#669 fix: console error in previews.js
  src/admin/previews.js
Labels: bug

#670 fix: update PWA plugin to Eleventy 2.0-compatible version
  eleventy.config.js
  package-lock.json
  package.json
  src/_includes/partials/global/service-worker.js
Labels: bug

#672 fix: redirect EDS page
  _redirects
Labels: bug

#673 chore(deps-dev): prevent Dependabot upgrades to stylelint
  .github/dependabot.yml
  .github/workflows/backstop.yml
  .github/workflows/lighthouse.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  package.json
Labels: dependencies

#688 feat: lint JS in Markdown
  .eslintrc.js
  package-lock.json
  package.json
Labels: enhancement

#689 fix: exclude CMS from sitemap
  src/admin/admin.njk
Labels: bug

#697 chore(deps-dev): adjust version pinning
  .github/dependabot.yml
  package.json
Labels: dependencies, javascript

#699 feat: replace Netlify CMS with Decap CMS
  eleventy.config.js
  package-lock.json
  package.json
  src/admin/admin.njk
Labels: dependencies, enhancement
