Repository inclusive-design/idrc, pull requests merged in 2023-07, with the labels that each got.

#642 Fix interaction styles for the navigation bar and the footer links
  package-lock.json
  package.json
  src/_includes/layouts/404.njk
  src/_includes/layouts/history.njk
  src/_includes/layouts/home.njk
  src/_includes/layouts/ideas.njk
  src/_includes/layouts/news.njk
  src/_includes/layouts/page--team.njk
  src/_includes/layouts/page.njk
  src/_includes/layouts/project.njk
  src/_includes/layouts/projects.njk
  src/_includes/layouts/resources.njk
  src/_includes/partials/components/page-header.njk
  src/assets/styles/app.scss
  src/assets/styles/base/_base.scss
  src/assets/styles/components/_nav.scss
  src/assets/styles/components/_page-header.scss
  src/assets/styles/layout/_footer.scss
  src/assets/styles/layout/_header.scss
  src/assets/styles/pages/_generic.scss
Labels: bug

#651 feat: update to eleventy-plugin-fluid asset processing
  .nvmrc
  eleventy.config.js
  package-lock.json
  package.json
  src/_includes/partials/global/scripts.njk
  src/_includes/partials/global/stylesheets.njk
  src/assets/scripts/_resources-utils.js
  src/assets/scripts/resources-dynamic-handler.js
  src/assets/styles/components/_nav.scss
  webpack.mix.js
Labels: dependencies, enhancement

#652 chore: update npm dependency
  .husky/commit-msg.txt
  .husky/pre-commit.txt
  eleventy.config.js
  package-lock.json
  package.json
  src/transforms/html-min.js
Labels: dependencies

#653 chore(deps): switch to main branch of eleventy-plugin-fluid
  package-lock.json
  package.json
Labels: dependencies

#654 fix: resolve page layout regression
  src/assets/styles/components/_page-header.scss
Labels: bug
